config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root "welcome#home"
get "about", to: "welcome#about"
get "profile", to: "welcome#profile"

resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
validates :title, presence:true
validates :description, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController< ApplicationController

def index
@articles= Article.all
end



def new
@article= Article.new
end

def edit
@article= Article.find(params[:id])
end

def create

@article=Article.new(article_params)

if @article.save
flash[:notice]="Article was successfully created"
redirect_to article_path(@article)
else
render "new"
end
end

def update
@article= Article.find(params[:id])
if @article.update(article_params)
flash[:notice]="Article was successfully update"
redirect_to article_path(@article)
else
render "edit"
end
end


def show
@article= Article.find(params[:id])
end

def destroy
@article= Article.find(params[:id])
@article.destroy
flash[:notice]="Article was successfully deleted"
redirect_to articles_path
end


private

def article_params
params.require(:article).permit(:title,:description)
end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def home

end

def about

end

def profile

end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Articles", articles_path %>

app/views/articles/index.html.erb
<h1>All the existing articles in store <h1>

<h3><%= link_to "Create New Article", new_article_path %></h3>

  <table>
    <tr>
      <th>Title</th>
      <th>Description</th>
    </tr>

<% @articles.each do |article|%>

<tr style="font-weight:100;">
  <td style="padding:10px; background-color:red;color:white;"> <%= article.title %> </td>
  <td style="padding:10px;background-color:blue;color:white;"> <%= article.description %> </td>
  <td style="padding:10px;background-color:green;color:white;text-decoration:none;"> <%= link_to "Edit", edit_article_path(article) %> </td>
  <td style="padding:10px;background-color:yellow;color:white; text-decoration:none;"> <%= link_to "Show", article_path(article) %> </td>
  <td style="padding:10px;background-color:orange;color:white; text-decoration:none;"> <%= link_to "Delete", article_path(article),method: :delete, data: {confirm:"Are you sure?"} %> </td>


</tr>

<% end %>

  </table>


<h4 style="background-color:gray;padding:5px;margin:10px; width:50px;"><%= link_to "Home", root_path %></h4>

app/views/articles/new.html.erb
<h1>Create a new article for your blog</h1>

<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to "Articles", articles_path %>

app/views/articles/show.html.erb
<h1> Showing selected article </h1>

<p> Title: <%= @article.title %> </p>

<p> Description: <%= @article.description %> </p>


<%= link_to "Edit", edit_article_path(@article) %>
<%= link_to "Articles", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h1>It is about page and working fine</h1>

<%= link_to "Home", root_path %>
<%= link_to "Profile",profile_path %>

<hr>

<h2>I am very happy about it</h2>

<ul>
<li>working fine 1</li>
<li>working fine 2</li>
<li>working fine 3</li>
<li>working fine 4</li>
<li>working fine 5</li>

</ul>

app/views/welcome/home.html.erb
<h1>Home: Feel free to browse all the articles </h1>


<h4 style="background-color:orange;padding:5px;margin:10px; width:100px;"><%= link_to "About",   about_path %></h4>
<h4 style="background-color:orange;padding:5px;margin:10px; width:100px;"><%= link_to "Profile", profile_path %></h4>
<h4 style="background-color:orange;padding:5px;margin:10px; width:100px;"><%= link_to "All articles", articles_path %></h4>

app/views/welcome/profile.html.erb
<h1>This is a profile for user</h1>

<h2>Name: unknown</h2>

<h3>Address: unknown</h3>
<h3>Contact: unknown</h3>

<hr>


<%= link_to "Home", root_path %>
<%= link_to "About",about_path %>